micronaut:
  application:
    name: pixKeyManagerRest
  server:
    context-path: ${BASE_PATH:api/pix}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
      plaintext: true
      max-retry-attempts: 10